export const authConstants = {
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE'
};

export const teamConstants = {
    TEAM_CREATE_REQUEST : 'TEAM_CREATE_REQUEST',
    TEAM_CREATE_SUCCESS : 'TEAM_CREATE_SUCCESS',
    TEAM_CREATE_FAILURE : 'TEAM_CREATE_FAILURE'
}
